from typing import Protocol


class EmbeddingProvider(Protocol):
    def provider_name(self) -> str: ...

    def vector_dim(self) -> int: ...

    def embed_one(self, text: str) -> list[float]: ...

    def embed_many(self, texts: list[str]) -> list[list[float]]: ...
